webapp/__init__.py
import logging

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_celery import Celery
from flask_debugtoolbar import DebugToolbarExtension
from flask_caching import Cache
from flask_assets import Environment, Bundle
from flask_mail import Mail
from flask_youtube import Youtube

logging.basicConfig(format="%(asctime)s:%(levelname)s:%(name)s:%(message)s")
logging.getLogger().setLevel(logging.DEBUG)
log = logging.getLogger(__name__)

db = SQLAlchemy()
migrate = Migrate()
celery = Celery()
debug_toolbar = DebugToolbarExtension()
cache = Cache()
assets_env = Environment()
mail = Mail()

youtube = Youtube()

main_css = Bundle("css/bootstrap.css",
                  filters="cssmin",
                  output="css/common.css")

main_js = Bundle("js/jquery.js", "js/bootstrap.js",
                 filters="jsmin",
                 output="js/common.js")


def page_not_found(error):
    return render_template("404.html"), 404


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/
    Arguments:
        object_name: the python path of the config object,
                     e.g. project.config.ProdConfig
    """
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    migrate.init_app(app, db)
    debug_toolbar.init_app(app)
    cache.init_app(app)
    assets_env.init_app(app)
    celery.init_app(app)
    mail.init_app(app)
    youtube.init_app(app)

    from .auth import create_module as auth_create_module
    from .blog import create_module as blog_create_module
    from .main import create_module as main_create_module
    from .api import create_module as api_create_module
    from .admin import create_module as admin_create_module
    from .babel import create_module as babel_create_module

    auth_create_module(app)
    blog_create_module(app)
    main_create_module(app)
    api_create_module(app)
    admin_create_module(app)
    babel_create_module(app)

    return app

webapp/admin/__init__.py
from flask_admin import Admin

from .. import db
from webapp.auth.models import Role, User
from webapp.blog.models import Tag, Comment, Reminder, Post
from .controllers import CustomView, CustomModelView, CustomFileAdmin, PostView

admin = Admin()


def create_module(app, **kwargs):
    admin.init_app(app)
    admin.add_view(CustomView(name="Custom"))

    models = [User, Role, Comment, Tag, Reminder]

    for model in models:
        admin.add_view(CustomModelView(model, db.session, category="Models"))

    admin.add_view(PostView(Post, db.session, category="Models"))
    admin.add_view(CustomFileAdmin(app.static_folder, "/static/",
                                   name="Static Files"))

webapp/admin/controllers.py
from flask_admin import BaseView, expose
from flask_admin.contrib.fileadmin import FileAdmin
from flask_admin.contrib.sqla import ModelView
from flask_login import login_required, current_user

from webapp.admin.forms import CKTextAreaField
from webapp.auth import has_role


class CustomView(BaseView):
    @expose("/")
    @login_required
    @has_role("admin")
    def index(self):
        return self.render("admin/custom.html")

    @expose("/second_page")
    @login_required
    @has_role("admin")
    def second_page(self):
        return self.render("admin/second_page.html")


class CustomModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_role("admin")


class PostView(CustomModelView):
    form_overrides = dict(text=CKTextAreaField)
    column_searchable_list = ("text", "title")
    column_filters = ("publish_date",)

    create_template = "admin/post_edit.html"
    edit_template = "admin/post_edit.html"


class CustomFileAdmin(FileAdmin):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_role("admin")

webapp/api/__init__.py
from flask_restful import Api
from .blog.controllers import PostApi, CommentApi, CommentsByPostApi

rest_api = Api()


def create_module(app, **kwargs):
    rest_api.add_resource(
        PostApi,
        "/api/post",
        "/api/post/<int:post_id>",
    )
    rest_api.add_resource(
        CommentApi,
        "/api/comment",
        "/api/comment/<int:comment_id>",
    )
    rest_api.add_resource(
        CommentsByPostApi,
        "/api/post/<int:post_id>/comment",
        "/api/post/<int:post_id>/comment/<int:comment_id>",
    )
    rest_api.init_app(app)

webapp/api/blog/controllers.py
import datetime

from flask import abort, current_app, jsonify, request
from flask_restful import Resource, fields, marshal_with
from flask_jwt_extended import jwt_required, get_jwt_identity

from webapp.blog.models import db, Post, Tag, Comment
from webapp.auth.models import User
from .parsers import (
    post_get_parser,
    post_post_parser,
    post_put_parser,
    comment_get_parser, comment_put_parser, comment_post_parser)
from .fields import HTMLField

nested_tag_fields = {
    "id": fields.Integer(),
    "title": fields.String()
}

comment_fields = {
    "id": fields.Integer(),
    "name": fields.String(),
    "text": fields.String(),
    "date": fields.DateTime(dt_format="iso8601"),
    "post_id": fields.Integer()
}

post_fields = {
    "id": fields.Integer(),
    "author": fields.String(attribute=lambda x: x.user.username),
    "title": fields.String(),
    "text": HTMLField(),
    "tags": fields.List(fields.Nested(nested_tag_fields)),
    "comments": fields.List(fields.Nested(comment_fields)),
    "publish_date": fields.DateTime(dt_format="iso8601")
}


def add_tags_to_post(post, tags_list):
    for item in tags_list:
        tag = Tag.query.filter_by(title=item).first()

        if tag:
            post.tags.append(tag)
        else:
            new_tag = Tag(item)
            post.tags.append(new_tag)


class PostApi(Resource):
    @marshal_with(post_fields)
    @jwt_required
    def get(self, post_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            return post
        else:
            args = post_get_parser.parse_args()
            page = args["page"] or 1

            if args["user"]:
                user = User.query.filter_by(usesrname=args["user"]).first()
                if not user:
                    abort(404)

                posts = user.posts.order_by(
                    Post.publish_date.desc()
                ).paginate(page, current_app.config["POSTS_PER_PAGE"])
            else:
                posts = Post.query.order_by(
                    Post.publish_date.desc()
                ).paginate(page, current_app.config["POSTS_PER_PAGE"])

            return posts.items

    @jwt_required
    def post(self):
        print(request.data)
        args = post_post_parser.parse_args(strict=True)
        new_post = Post(args["title"])
        new_post.user_id = get_jwt_identity()
        new_post.text = args["text"]

        if args["tags"]:
            add_tags_to_post(new_post, args["tags"])

        db.session.add(new_post)
        db.session.commit()
        return {"id": new_post.id}, 201

    @jwt_required
    def put(self, post_id=None):
        if not post_id:
            abort(400)
        post = Post.query.get(post_id)
        if not post:
            abort(404)
        args = post_put_parser.parse_args(strict=True)
        if get_jwt_identity() != post.user_id:
            abort(403)
        if args["title"]:
            post.title = args["title"]
        if args["text"]:
            post.text = args["text"]
        if args["tags"]:
            print(f"Tags {args['tags']}")
            add_tags_to_post(post, args["tags"])

        db.session.merge(post)
        db.session.commit()
        return {"id": post.id}, 201

    @jwt_required
    def delete(self, post_id=None):
        if not post_id:
            abort(400)
        post = Post.query.get(post_id)
        if not post:
            abort(404)
        if get_jwt_identity() != post.user_id:
            abort(401)

        db.session.delete(post)
        db.session.commit()
        return "", 204


class CommentsByPostApi(Resource):
    @marshal_with(comment_fields)
    @jwt_required
    def get(self, post_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            args = comment_get_parser.parse_args()
            page = args["page"] or 1

            comments = post.comments.order_by(
                Comment.date.desc()
            ).paginate(page, current_app.config["POSTS_PER_PAGE"])
            if not comments:
                abort(404)
            return comments.items
        else:
            abort(404)

    @jwt_required
    def post(self, post_id=None):
        print(request.data)
        if post_id:
            if Post.query.filter_by(id=post_id).count() < 1:
                abort(404)
            args = comment_post_parser.parse_args(strict=True)
            user = User.query.get(get_jwt_identity())
            new_comment = Comment(name=user.username, text=args["text"])
            new_comment.post_id = post_id

            db.session.add(new_comment)
            db.session.commit()
            return {"id": new_comment.id}, 201
        else:
            abort(404)

    @jwt_required
    def put(self, post_id=None, comment_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            comment = post.comments.filter_by(id=comment_id).one()
            if not comment:
                abort(404)
            args = comment_put_parser.parse_args(strict=True)
            if args["text"]:
                comment.text = args["text"]

            db.session.merge(comment)
            db.session.commit()
            return {"post_id": post_id, "id": comment.id}, 201
        else:
            abort(404)

    @jwt_required
    def delete(self, post_id=None, comment_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            comment = post.comments.filter_by(id=comment_id).one()
            if not comment:
                abort(404)

            db.session.delete(comment)
            db.session.commit()
            return "", 204
        else:
            abort(404)


class CommentApi(Resource):
    @marshal_with(comment_fields)
    @jwt_required
    def get(self, comment_id=None):
        if comment_id:
            comment = Comment.query.get(comment_id)
            if not comment:
                abort(404)
            return comment
        else:
            args = comment_get_parser.parse_args()
            page = args["page"] or 1

            comments = Comment.query.order_by(
                Comment.date.desc()
            ).paginate(page, current_app.config["POSTS_PER_PAGE"])

            return comments.items

    @jwt_required
    def put(self, comment_id=None):
        if not comment_id:
            abort(400)
        comment = Comment.query.get(comment_id)
        if not comment:
            abort(404)
        args = comment_put_parser.parse_args(strict=True)
        if args["text"]:
            comment.text = args["text"]

        db.session.merge(comment)
        db.session.commit()
        return {"id": comment.id}, 201

    @jwt_required
    def delete(self, comment_id=None):
        if not comment_id:
            abort(400)
        comment = Comment.query.get(comment_id)
        if not comment:
            abort(404)

        db.session.delete(comment)
        db.session.commit()
        return "", 204

webapp/babel/__init__.py
from flask import request, current_app, has_request_context, session
from flask_babel import Babel

babel = Babel()


@babel.localeselector
def get_locale():
    if has_request_context():
        locale = session.get('locale')
    if locale:
        return locale
    session['locale'] = 'en'
    return session['locale']

    # return request.accept_languages.best_match(current_app.config["LANGUAGES"])


def create_module(app, **kwargs):
    babel.init_app(app)

    from .controllers import babel_blueprint
    app.register_blueprint(babel_blueprint)

webapp/babel/controllers.py
from flask import Blueprint, session, redirect, url_for

babel_blueprint = Blueprint("babel", __name__, url_prefix="/babel")


@babel_blueprint.route("<string:locale>")
def index(locale):
    session["locale"] = locale
    return redirect(url_for("blog.home"))

webapp/blog/__init__.py
from sqlalchemy import event

from .models import db, Reminder
from .tasks import on_reminder_save


def create_module(app, **kwargs):
    event.listen(Reminder, "after_insert", on_reminder_save)
    from .controllers import blog_blueprint
    app.register_blueprint(blog_blueprint)

webapp/blog/controllers.py
import datetime

from sqlalchemy import func, desc
from flask import render_template, Blueprint, flash, redirect, url_for, \
    current_app, abort, request, get_flashed_messages, session
from flask_login import login_required, current_user

from .models import db, Post, Tag, Comment, tags
from .forms import CommentForm, PostForm
from ..auth.models import User
from ..auth import has_role
from .. import cache

blog_blueprint = Blueprint("blog", __name__,
                           template_folder="../templates/blog",
                           url_prefix="/blog")


def make_cache_key(*args, **kwargs):
    path = request.path
    args = str(hash(frozenset(request.args.items())))
    messages = str(hash(frozenset(get_flashed_messages())))
    if current_user.is_authenticated:
        roles = str(current_user.roles)
    else:
        roles = ""
    return (path + args + roles + session.get("locale", "") + messages)\
        .encode("utf-8")


@cache.cached(timeout=7200, key_prefix="sidebar_data")
def sidebar_data():
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label("total")).join(tags) \
        .group_by(Tag).order_by(desc("total")).limit(5).all()
    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
@cache.cached(timeout=60)
def home(page=1):
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(
        page, current_app.config.get("POSTS_PER_PAGE", 10), False)
    recent, top_tags = sidebar_data()

    return render_template("home.html", posts=posts, recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route("/new", methods=["GET", "POST"])
@login_required
@has_role("poster")
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post()
        new_post.title = form.title.data
        new_post.user_id = current_user.id
        new_post.text = form.text.data
        new_post.youtube_id = form.youtube_id.data
        db.session.add(new_post)
        db.session.commit()
        flash("Post added", "info")
        return redirect(url_for(".post", post_id=new_post.id))
    return render_template("new.html", form=form)


@blog_blueprint.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    if current_user.id == post.user.id:
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.text = form.text.data
            post.youtube_id = form.youtube_id.data
            post.publish_date = datetime.datetime.now()
            db.session.merge(post)
            db.session.commit()
            return redirect(url_for(".post", post_id=post.id))
        form.title.data = post.title
        form.youtube_id.data = post.youtube_id
        form.text.data = post.text
        return render_template("edit.html", form=form, post=post)
    abort(403)


@blog_blueprint.route("/post/<int:post_id>", methods=["GET", "POST"])
@cache.cached(timeout=60, key_prefix=make_cache_key)
def post(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        try:
            db.session.add(new_comment)
            db.session.commit()
        except Exception as e:
            flash(f"Error adding your comment: {str(e)}", "error")
            db.session.rollback()
        else:
            flash("Comment added", "info")
        return redirect(url_for("blog.post", post_id=post_id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template("post.html", post=post, tags=tags,
                           comments=comments, recent=recent, top_tags=top_tags,
                           form=form)


@blog_blueprint.route("/posts_by_tag/<string:tag_name>")
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_tag(tag_name):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template("tag.html", tag=tag, posts=posts, recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route("/posts_by_user/<string:username>")
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template("user.html", user=user, posts=posts, recent=recent,
                           top_tags=top_tags)

webapp/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Blog{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
</head>
<body>
{% include "blog/navbar.html" %}
<div class="container">
  <div class="row row-lg-4">
    <div class="col">
      {% block head %}
        {% include "blog/head.html" %}
      {% endblock %}
    </div>
  </div>
  {% include "blog/messages.html" %}
  {% block body %}
    <div class="row">
      <div class="col-lg-9">
        {% block leftbody %}{% endblock %}
      </div>
      <div class="col-lg-3 rounded">
        {% block rightbody %}
          {% include "blog/rightbody.html" %}
        {% endblock %}
      </div>
    </div>
  {% endblock %}
  {% include "blog/footer.html" %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</html>

webapp/templates/blog/edit.html
{% extends "base.html" %}
{% block title %}Post Creation{% endblock %}
{% block body %}
  <div class="p-4 shadow-sm">
    <div class="row">
      <div class="col">
        <h1>Edit Post</h1>
      </div>
    </div>

    <div class="row">
      <form method="POST" action="{{ url_for('.edit_post', id=post.id) }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.title.label }}
          {% if form.title.errors %}
            {% for e in form.title.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.title(class_='form-control') }}
        </div>
        <div class="form-group">
          {{ form.youtube_id.label }}
          {% if form.youtube_id.errors %}
            {% for e in form.youtube_id.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.youtube_id(class_='form-control') }}
        </div>
        <div class="form-group">
          {{ form.text.label }}
          {% if form.text.errors %}
            {% for e in form.text.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.text(id="editor", class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endblock %}

{% block js %}
  <script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
  </script>
  <script>
    CKEDITOR.replace('editor');
  </script>
{% endblock %}

webapp/templates/blog/home.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Home{% endblock %}

{% block leftbody %}
  {{ macros.render_posts(posts) }}
  {{ macros.render_pagination(posts, "blog.home") }}
{% endblock %}

webapp/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('blog.home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('blog.home')}}"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i class="fa fa-fw fa-sign-in"></i>Register</a>
            </li>
        </ul>
    </div>
</nav>

webapp/templates/blog/new.html
{% extends "base.html" %}
{% block title %}Post Creation{% endblock %}
{% block body %}
  <div class="p-4 shadow-sm">
    <div class="row">
      <div class="col">
        <h1>Create a New Post</h1>
      </div>
    </div>

    <div class="row">
      <form method="POST" action="{{ url_for('.new_post') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.title.label }}
          {% if form.title.errors %}
            {% for e in form.title.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.title(class_='form-control') }}
        </div>
        <div class="form-group">
          {{ form.youtube_id.label }}
          {% if form.youtube_id.errors %}
            {% for e in form.youtube_id.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.youtube_id(class_='form-control') }}
        </div>
        <div class="form-group">
          {{ form.text.label }}
          {% if form.text.errors %}
            {% for e in form.text.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.text(id="editor", class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endblock %}

{% block js %}
  <script src="https://cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
  </script>
  <script>
    CKEDITOR.replace('editor');
  </script>
{% endblock %}

webapp/templates/blog/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block leftbody %}
  <div class="p-4 shadow-sm">
    <div class="row">
      <div class="col">
        <h1>{{ post.title }}</h1>
      </div>
    </div>
    <div class="row shadow-sm">
      <div class="col-lg-6">
        <p>Written By <a
            href="{{ url_for('blog.posts_by_user', username=post.user.username) }}">{{ post.user.username }}</a>
          on {{ post.publish_date }}</p>
      </div>
      <div class="col-lg-6">
        <p class="text-right"> Tags: {% for tag in tags %}
          <a href="{{ url_for('blog.posts_by_tag', tag_name=tag.title) }}">{{ tag.title }}</a>
        {% endfor %}
        </p>
      </div>
    </div>
    {% if post.youtube_id %}
      <div class="row">
        <div class="col">
          {{ youtube(post.youtube_id) | safe }}
        </div>
      </div>
    {% endif %}
    <div class="row">
      <div class="col">
        {{ post.text | safe }}
      </div>
    </div>
    {% if current_user.id == post.user_id %}
      <div class="col-lg-2">
        <a href="{{ url_for('.edit_post', id=post.id) }}" class="btn
       btn-primary">Edit</a>
      </div>
    {% endif %}
  </div>
  <div class="p-4 shadow-sm">
    <div class="row">
      <div class="col">
        <h4>New Comment:</h4>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
          {{ form.hidden_tag() }}
          <div class="form-group">
            {{ form.name.label }}
            {% if form.name.errors %}
              {% for e in form.name.errors %}
                <p class="help-block">{{ e }}</p>
              {% endfor %}
            {% endif %}
            {{ form.name(class_='form-control') }}
          </div>
          <div class="form-group">
            {{ form.text.label }}
            {% if form.text.errors %}
              {% for e in form.text.errors %}
                <p class="help-block">{{ e }}</p>
              {% endfor %}
            {% endif %}
            {{ form.text(class_='form-control') }}
          </div>
          <input class="btn btn-primary" type="submit" value="Add Comment">
        </form>
      </div>
    </div>
  </div>
  <div class="p-4 shadow-sm">
    <div class="row">
      <div class="col">
        <h4>Comments ({{ comments | length }})</h4>
      </div>
    </div>
    <div class="row p-2">
      <div class="col">
        {% if comments | length == 0 %}
          <p>There are no comments for this post.</p>
        {% else %}
          {% for comment in comments %}
            <div class="shadow-sm p-2">
              <dt>By: {{ comment.name }} on {{ comment.date }}</dt>
              <dd>{{ comment.text }}</dd>
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

webapp/templates/blog/rightbody.html
<div class="row">
  <div class="col">
    <h5>Recent Posts</h5>
  </div>
</div>
<ul class="list-group">
  {% for post in recent %}
    <li class="list-group-item">
      <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
<div class="row">
  <div class="col">
    <h5>Popular Tags</h5>
  </div>
</div>
<ul class="list-group">
  {% for tag in top_tags %}
    <li class="list-group-item"
    ><a href="{{ url_for('blog.posts_by_tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a>
    </li>
  {% endfor %}
</ul>

webapp/templates/blog/tag.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}{{ tag.title }}{% endblock %}
{% block leftbody %}
  <div class="row">
    <div class="col bg-light">
      <h1 class="text-center">Posts With Tag {{ tag.title }}</h1>
    </div>
  </div>
  {{ macros.render_posts(posts, pagination=False) }}
{% endblock %}

webapp/templates/blog/user.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ user.username }}'s Posts{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts By {{ user.username }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}
{% endblock %}