webapp/__init__.py
import logging

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_celery import Celery
from flask_debugtoolbar import DebugToolbarExtension
from flask_caching import Cache
from flask_assets import Environment, Bundle
from flask_mail import Mail
from flask_youtube import Youtube

logging.basicConfig(format="%(asctime)s:%(levelname)s:%(name)s:%(message)s")
logging.getLogger().setLevel(logging.DEBUG)
log = logging.getLogger(__name__)

db = SQLAlchemy()
migrate = Migrate()
celery = Celery()
debug_toolbar = DebugToolbarExtension()
cache = Cache()
assets_env = Environment()
mail = Mail()

youtube = Youtube()

main_css = Bundle("css/bootstrap.css",
                  filters="cssmin",
                  output="css/common.css")

main_js = Bundle("js/jquery.js", "js/bootstrap.js",
                 filters="jsmin",
                 output="js/common.js")


def page_not_found(error):
    return render_template("404.html"), 404


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/
    Arguments:
        object_name: the python path of the config object,
                     e.g. project.config.ProdConfig
    """
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    migrate.init_app(app, db)
    debug_toolbar.init_app(app)
    cache.init_app(app)
    assets_env.init_app(app)
    celery.init_app(app)
    mail.init_app(app)
    youtube.init_app(app)

    from .auth import create_module as auth_create_module
    from .blog import create_module as blog_create_module
    from .main import create_module as main_create_module
    from .api import create_module as api_create_module
    from .admin import create_module as admin_create_module
    from .babel import create_module as babel_create_module

    auth_create_module(app)
    blog_create_module(app)
    main_create_module(app)
    api_create_module(app)
    admin_create_module(app)
    babel_create_module(app)

    return app

webapp/admin/__init__.py
from flask_admin import Admin

from .. import db
from webapp.auth.models import Role, User
from webapp.blog.models import Tag, Comment, Reminder, Post
from .controllers import CustomView, CustomModelView, CustomFileAdmin, PostView

admin = Admin()


def create_module(app, **kwargs):
    admin.init_app(app)
    admin.add_view(CustomView(name="Custom"))

    models = [User, Role, Comment, Tag, Reminder]

    for model in models:
        admin.add_view(CustomModelView(model, db.session, category="Models"))

    admin.add_view(PostView(Post, db.session, category="Models"))
    admin.add_view(CustomFileAdmin(app.static_folder, "/static/",
                                   name="Static Files"))

webapp/admin/controllers.py
from flask_admin import BaseView, expose
from flask_admin.contrib.fileadmin import FileAdmin
from flask_admin.contrib.sqla import ModelView
from flask_login import login_required, current_user

from webapp.admin.forms import CKTextAreaField
from webapp.auth import has_role


class CustomView(BaseView):
    @expose("/")
    @login_required
    @has_role("admin")
    def index(self):
        return self.render("admin/custom.html")

    @expose("/second_page")
    @login_required
    @has_role("admin")
    def second_page(self):
        return self.render("admin/second_page.html")


class CustomModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_role("admin")


class PostView(CustomModelView):
    form_overrides = dict(text=CKTextAreaField)
    column_searchable_list = ("text", "title")
    column_filters = ("publish_date",)

    create_template = "admin/post_edit.html"
    edit_template = "admin/post_edit.html"


class CustomFileAdmin(FileAdmin):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.has_role("admin")

webapp/api/__init__.py
from flask_restful import Api
from .blog.controllers import PostApi, CommentApi, CommentsByPostApi

rest_api = Api()


def create_module(app, **kwargs):
    rest_api.add_resource(
        PostApi,
        "/api/post",
        "/api/post/<int:post_id>",
    )
    rest_api.add_resource(
        CommentApi,
        "/api/comment",
        "/api/comment/<int:comment_id>",
    )
    rest_api.add_resource(
        CommentsByPostApi,
        "/api/post/<int:post_id>/comment",
        "/api/post/<int:post_id>/comment/<int:comment_id>",
    )
    rest_api.init_app(app)

webapp/api/blog/controllers.py
import datetime

from flask import abort, current_app, jsonify, request
from flask_restful import Resource, fields, marshal_with
from flask_jwt_extended import jwt_required, get_jwt_identity

from webapp.blog.models import db, Post, Tag, Comment
from webapp.auth.models import User
from .parsers import (
    post_get_parser,
    post_post_parser,
    post_put_parser,
    comment_get_parser, comment_put_parser, comment_post_parser)
from .fields import HTMLField

nested_tag_fields = {
    "id": fields.Integer(),
    "title": fields.String()
}

comment_fields = {
    "id": fields.Integer(),
    "name": fields.String(),
    "text": fields.String(),
    "date": fields.DateTime(dt_format="iso8601"),
    "post_id": fields.Integer()
}

post_fields = {
    "id": fields.Integer(),
    "author": fields.String(attribute=lambda x: x.user.username),
    "title": fields.String(),
    "text": HTMLField(),
    "tags": fields.List(fields.Nested(nested_tag_fields)),
    "comments": fields.List(fields.Nested(comment_fields)),
    "publish_date": fields.DateTime(dt_format="iso8601")
}


def add_tags_to_post(post, tags_list):
    for item in tags_list:
        tag = Tag.query.filter_by(title=item).first()

        if tag:
            post.tags.append(tag)
        else:
            new_tag = Tag(item)
            post.tags.append(new_tag)


class PostApi(Resource):
    @marshal_with(post_fields)
    @jwt_required
    def get(self, post_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            return post
        else:
            args = post_get_parser.parse_args()
            page = args["page"] or 1

            if args["user"]:
                user = User.query.filter_by(usesrname=args["user"]).first()
                if not user:
                    abort(404)

                posts = user.posts.order_by(
                    Post.publish_date.desc()
                ).paginate(page, current_app.config["POSTS_PER_PAGE"])
            else:
                posts = Post.query.order_by(
                    Post.publish_date.desc()
                ).paginate(page, current_app.config["POSTS_PER_PAGE"])

            return posts.items

    @jwt_required
    def post(self):
        print(request.data)
        args = post_post_parser.parse_args(strict=True)
        new_post = Post(args["title"])
        new_post.user_id = get_jwt_identity()
        new_post.text = args["text"]

        if args["tags"]:
            add_tags_to_post(new_post, args["tags"])

        db.session.add(new_post)
        db.session.commit()
        return {"id": new_post.id}, 201

    @jwt_required
    def put(self, post_id=None):
        if not post_id:
            abort(400)
        post = Post.query.get(post_id)
        if not post:
            abort(404)
        args = post_put_parser.parse_args(strict=True)
        if get_jwt_identity() != post.user_id:
            abort(403)
        if args["title"]:
            post.title = args["title"]
        if args["text"]:
            post.text = args["text"]
        if args["tags"]:
            print(f"Tags {args['tags']}")
            add_tags_to_post(post, args["tags"])

        db.session.merge(post)
        db.session.commit()
        return {"id": post.id}, 201

    @jwt_required
    def delete(self, post_id=None):
        if not post_id:
            abort(400)
        post = Post.query.get(post_id)
        if not post:
            abort(404)
        if get_jwt_identity() != post.user_id:
            abort(401)

        db.session.delete(post)
        db.session.commit()
        return "", 204


class CommentsByPostApi(Resource):
    @marshal_with(comment_fields)
    @jwt_required
    def get(self, post_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            args = comment_get_parser.parse_args()
            page = args["page"] or 1

            comments = post.comments.order_by(
                Comment.date.desc()
            ).paginate(page, current_app.config["POSTS_PER_PAGE"])
            if not comments:
                abort(404)
            return comments.items
        else:
            abort(404)

    @jwt_required
    def post(self, post_id=None):
        print(request.data)
        if post_id:
            if Post.query.filter_by(id=post_id).count() < 1:
                abort(404)
            args = comment_post_parser.parse_args(strict=True)
            user = User.query.get(get_jwt_identity())
            new_comment = Comment(name=user.username, text=args["text"])
            new_comment.post_id = post_id

            db.session.add(new_comment)
            db.session.commit()
            return {"id": new_comment.id}, 201
        else:
            abort(404)

    @jwt_required
    def put(self, post_id=None, comment_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            comment = post.comments.filter_by(id=comment_id).one()
            if not comment:
                abort(404)
            args = comment_put_parser.parse_args(strict=True)
            if args["text"]:
                comment.text = args["text"]

            db.session.merge(comment)
            db.session.commit()
            return {"post_id": post_id, "id": comment.id}, 201
        else:
            abort(404)

    @jwt_required
    def delete(self, post_id=None, comment_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            comment = post.comments.filter_by(id=comment_id).one()
            if not comment:
                abort(404)

            db.session.delete(comment)
            db.session.commit()
            return "", 204
        else:
            abort(404)


class CommentApi(Resource):
    @marshal_with(comment_fields)
    @jwt_required
    def get(self, comment_id=None):
        if comment_id:
            comment = Comment.query.get(comment_id)
            if not comment:
                abort(404)
            return comment
        else:
            args = comment_get_parser.parse_args()
            page = args["page"] or 1

            comments = Comment.query.order_by(
                Comment.date.desc()
            ).paginate(page, current_app.config["POSTS_PER_PAGE"])

            return comments.items

    @jwt_required
    def put(self, comment_id=None):
        if not comment_id:
            abort(400)
        comment = Comment.query.get(comment_id)
        if not comment:
            abort(404)
        args = comment_put_parser.parse_args(strict=True)
        if args["text"]:
            comment.text = args["text"]

        db.session.merge(comment)
        db.session.commit()
        return {"id": comment.id}, 201

    @jwt_required
    def delete(self, comment_id=None):
        if not comment_id:
            abort(400)
        comment = Comment.query.get(comment_id)
        if not comment:
            abort(404)

        db.session.delete(comment)
        db.session.commit()
        return "", 204

webapp/babel/__init__.py
from flask import request, current_app, has_request_context, session
from flask_babel import Babel

babel = Babel()


@babel.localeselector
def get_locale():
    if has_request_context():
        locale = session.get('locale')
    if locale:
        return locale
    session['locale'] = 'en'
    return session['locale']

    # return request.accept_languages.best_match(current_app.config["LANGUAGES"])


def create_module(app, **kwargs):
    babel.init_app(app)

    from .controllers import babel_blueprint
    app.register_blueprint(babel_blueprint)

webapp/babel/controllers.py
from flask import Blueprint, session, redirect, url_for

babel_blueprint = Blueprint("babel", __name__, url_prefix="/babel")


@babel_blueprint.route("<string:locale>")
def index(locale):
    session["locale"] = locale
    return redirect(url_for("blog.home"))

webapp/blog/__init__.py
from sqlalchemy import event

from .models import db, Reminder
from .tasks import on_reminder_save


def create_module(app, **kwargs):
    event.listen(Reminder, "after_insert", on_reminder_save)
    from .controllers import blog_blueprint
    app.register_blueprint(blog_blueprint)

webapp/blog/controllers.py
import datetime

from sqlalchemy import func, desc
from flask import render_template, Blueprint, flash, redirect, url_for, \
    current_app, abort, request, get_flashed_messages, session
from flask_login import login_required, current_user

from .models import db, Post, Tag, Comment, tags
from .forms import CommentForm, PostForm
from ..auth.models import User
from ..auth import has_role
from .. import cache

blog_blueprint = Blueprint("blog", __name__,
                           template_folder="../templates/blog",
                           url_prefix="/blog")


def make_cache_key(*args, **kwargs):
    path = request.path
    args = str(hash(frozenset(request.args.items())))
    messages = str(hash(frozenset(get_flashed_messages())))
    if current_user.is_authenticated:
        roles = str(current_user.roles)
    else:
        roles = ""
    return (path + args + roles + session.get("locale", "") + messages)\
        .encode("utf-8")


@cache.cached(timeout=7200, key_prefix="sidebar_data")
def sidebar_data():
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label("total")).join(tags) \
        .group_by(Tag).order_by(desc("total")).limit(5).all()
    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
@cache.cached(timeout=60)
def home(page=1):
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(
        page, current_app.config.get("POSTS_PER_PAGE", 10), False)
    recent, top_tags = sidebar_data()

    return render_template("home.html", posts=posts, recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route("/new", methods=["GET", "POST"])
@login_required
@has_role("poster")
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post()
        new_post.title = form.title.data
        new_post.user_id = current_user.id
        new_post.text = form.text.data
        new_post.youtube_id = form.youtube_id.data
        db.session.add(new_post)
        db.session.commit()
        flash("Post added", "info")
        return redirect(url_for(".post", post_id=new_post.id))
    return render_template("new.html", form=form)


@blog_blueprint.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    if current_user.id == post.user.id:
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.text = form.text.data
            post.youtube_id = form.youtube_id.data
            post.publish_date = datetime.datetime.now()
            db.session.merge(post)
            db.session.commit()
            return redirect(url_for(".post", post_id=post.id))
        form.title.data = post.title
        form.youtube_id.data = post.youtube_id
        form.text.data = post.text
        return render_template("edit.html", form=form, post=post)
    abort(403)


@blog_blueprint.route("/post/<int:post_id>", methods=["GET", "POST"])
@cache.cached(timeout=60, key_prefix=make_cache_key)
def post(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        try:
            db.session.add(new_comment)
            db.session.commit()
        except Exception as e:
            flash(f"Error adding your comment: {str(e)}", "error")
            db.session.rollback()
        else:
            flash("Comment added", "info")
        return redirect(url_for("blog.post", post_id=post_id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template("post.html", post=post, tags=tags,
                           comments=comments, recent=recent, top_tags=top_tags,
                           form=form)


@blog_blueprint.route("/posts_by_tag/<string:tag_name>")
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_tag(tag_name):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template("tag.html", tag=tag, posts=posts, recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route("/posts_by_user/<string:username>")
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template("user.html", user=user, posts=posts, recent=recent,
                           top_tags=top_tags)

webapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Blog{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
</head>
<body>
{% include "navbar.html" %}
<div class="container">
  <div class="row row-lg-4">
    <div class="col">
      {% block head %}
        {% include "head.html" %}
      {% endblock %}
    </div>
  </div>
  {% include "messages.html" %}
  {% block body %}
    <div class="row">
      <div class="col-lg-9">
        {% block leftbody %}{% endblock %}
      </div>
      <div class="col-lg-3 rounded">
        {% block rightbody %}
          {% include "rightbody.html" %}
        {% endblock %}
      </div>
    </div>
  {% endblock %}
  {% include "footer.html" %}
</div>
</body>
{% block js %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</html>

webapp/templates/digest.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Weekly Digest</title>
</head>
<body>
<table align="center"
       border="0"
       cellpadding="0"
       cellspacing="0"
       width="500px">
  <tr>
    <td style="font-size: 32px; font-family: Helvetica, sans-serif; color: #444;
    text-align: center; line-height: 1.65">
      Weekly Digest
    </td>
  </tr>
  {% for post in posts %}
    <tr>
      <td style="font-size: 24px; font-family: sans-serif; color: #444; text-align: center; line-height: 1.65">
        {{ post.title }}
      </td>
    </tr>
    <tr>
      <td style="font-size: 14px; font-family: serif; color: #444; line-height:1.65">
        {{ post.text | truncate(500) | safe }}
      </td>
    </tr>
    <tr>
      <td style="font-size: 12px; font-family: serif; color: blue; margin-bottom: 20px">
        <a href="{{ url_for('.post', post_id=post.id) }}">Read More</a>
      </td>
    </tr>
  {% endfor %}
</table>
</body>
</html>

webapp/templates/generic_list.html
{% extends "blog/base.html" %}

{% block body %}
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      {% for obj in objects %}
        <tr>
          {% for col in columns %}
            <td>
              {{ col }} {{ obj[col] }}
            </td>
          {% endfor %}
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

webapp/templates/head.html
<div class="container bg-info rounded">
  <center>
    <i class="fas fa-comments fa-5x"></i>
    <h1><a href="{{ url_for("blog.home") }}" class="text-white">My Blog</a></h1>
    <p>Welcome to the blog!</p>
  </center>
</div>

webapp/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if pagination.has_prev %}
        <li class="page-item">
          <a class="page-link" href="{{ url_for('blog.home', page=pagination.prev().page) }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
      {% endif %}
      {% for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li class="page-item">
              <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
            </li>
          {% else %}
            <li class="page-item active">
              <a class="page-link" href="">{{ page }}</a>
            </li>
          {% endif %}
        {% else %}
          <li class="page-item">
            <a class="page-link">…</a>
          <li>
        {% endif %}
      {% endfor %}
      {% if pagination.has_next %}
        <li class="page-item">
          <a class="page-link" href="{{ url_for('blog.home', page=pagination.next().page) }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endmacro %}

{% macro render_posts(posts, pagination=True) %}
  {% if pagination %}
    {% set _posts = posts.items %}
  {% else %}
    {% set _posts = posts %}
  {% endif %}

  {% for post in _posts %}
    <div>
      <h1>
        <a href="{{ url_for("blog.post", post_id=post.id) }}" class="text-dark">
          {{ post.title }}
        </a>
      </h1>
    </div>
    <div class="row">
      <div class="col">
        {{ post.text | truncate(500) | safe }}
        <a href="{{ url_for("blog.post", post_id=post.id) }}">Read More</a>
      </div>
    </div>
  {% endfor %}
{% endmacro %}

webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert">
        <button class="close" type="button" data-dismiss="alert"
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('blog.home') }}">{{ _("Home") }} <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown"
             role="button" data-toggle="dropdown">{{ _("Lang") }}</a>
          <div class="dropdown-menu">
            <a href="{{ url_for("babel.index", locale="en") }}" class="dropdown-item">en</a>
            <a href="{{ url_for("babel.index", locale="ru") }}" class="dropdown-item">ru</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('blog.home') }}"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for("auth.logout") }}">
            <i class="fa fa-fw fa-sign-out"></i>{{ _("Logout") }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for("auth.login") }}">
            <i class="fa fa-fw fa-sign-in"></i>{{ _("Login") }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for("auth.register") }}">
            <i class="fa fa-fw fa-sign-in"></i>{{ _("Register") }}</a>
        </li>
        {% if current_user.is_authenticated and current_user.has_role("admin") %}
          <li class="nav-item">
            <a href="{{ url_for("admin.index") }}" class="nav-link">
              {{ _("Admin") }}<span class="sr-only">(current)</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>